services:
  devhabit.api:
    container_name: devhabit.api
    image: ${DOCKER_REGISTRY-}devhabit.api:${DOCKER_IMAGE_TAG}
    build:
      context: .
      dockerfile: src/DevHabit.Api/Dockerfile
      target: ${DOCKER_BUILD_TARGET}
      args:
        - BUILD_CONFIGURATION=${DOCKER_ASPNETCORE_BUILD_CONFIGURATION}
    ports:
      - 5000:${ASPNETCORE_HTTP_PORTS}
      - 5001:${ASPNETCORE_HTTPS_PORTS}
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: ${DOTNET_USE_POLLING_FILE_WATCHER}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
      ASPNETCORE_HTTPS_PORTS: ${ASPNETCORE_HTTPS_PORTS}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_Kestrel__Certificates__Default__Path}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_Kestrel__Certificates__Default__Password}
      ConnectionStrings__Database: "Server=devhabit.postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
    depends_on:
      devhabit.postgres:
        condition: service_healthy
        restart: true

  devhabit.postgres:
    container_name: devhabit.postgres
    image: postgres:17.3-alpine3.21
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 10s
      interval: 10s
      retries: 3
      timeout: 10s

  devhabit.pgadmin:
    container_name: devhabit.pgadmin
    image: dpage/pgadmin4:9.2.0
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-data:/certs/server.cert
      - pgadmin-data:/certs/server.key
      - pgadmin-data:/pgadmin4/servers.json
    depends_on:
      devhabit.postgres:
        condition: service_healthy
        restart: true

  devhabit.seq:
    container_name: devhabit.seq
    image: datalust/seq:2024.3
    restart: unless-stopped
    ports:
      - 7080:80
      - 5341:5341
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq-data:/data

  devhabit.aspire-dashboard:
    container_name: devhabit.aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.1
    ports:
      - 18888:18888
      - 18889:18889
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"

volumes:
  postgres-data:
  pgadmin-data:
    external: true
  seq-data:
