services:
  devhabit.postgres:
    container_name: devhabit.postgres
    image: postgres:17.5-alpine3.21
    restart: unless-stopped
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 10s
      interval: 10s
      retries: 3
      timeout: 10s

  devhabit.pgadmin:
    container_name: devhabit.pgadmin
    image: dpage/pgadmin4:9.4.0
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-data:/certs/server.cert
      - pgadmin-data:/certs/server.key
      - pgadmin-data:/pgadmin4/servers.json
    depends_on:
      devhabit.postgres:
        condition: service_healthy
        restart: true

  devhabit.seq:
    container_name: devhabit.seq
    image: datalust/seq:2025.1
    restart: unless-stopped
    ports:
      - 7080:80
      - 5341:5341
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - seq-data:/data

  devhabit.aspire-dashboard:
    container_name: devhabit.aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.2
    ports:
      - 18888:18888
      - 18889:18889
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"

volumes:
  postgres-data:
  pgadmin-data:
    external: true
  seq-data:
