@habitId = h_01972355-6f47-7227-9838-0ca60418594f
@basePath = api/habits/{{habitId}}/tags
@tagId = t_01972353-5acd-7aef-918d-0b73a3904d94

### Upsert Habit Tags
PUT {{devHabitApiHostAddress}}/{{basePath}}
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "tagIds": [
    "t_01972353-7877-7cec-b0b7-f833abdbfd7a",
    "t_01972353-5acd-7aef-918d-0b73a3904d94"
  ]
}

### Delete Habit Tag
Delete {{devHabitApiHostAddress}}/{{basePath}}/{{tagId}}
Authorization: Bearer {{token}}
Accept: application/json
