@DevHabitApiHostAddress = https://localhost:5001
@BasePath = api/habits
@ResourceId = h_01962bc2-765b-7e35-846e-42568b36975b

### Get Habits
GET {{DevHabitApiHostAddress}}/{{BasePath}}
Accept: application/json

### Get Habit by Id
GET {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}}
Accept: application/json

### Create Habit
POST {{DevHabitApiHostAddress}}/{{BasePath}}
Accept: application/json
Content-Type: application/json

{
  "name": null,
  "description": null,
  "type": 2,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 30,
    "unit": "minutes"
  }
}

### Update Habit
PUT {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}}
Accept: application/json
Content-Type: application/json

{
  "name": "Daily Coding",
  "description": "The new description",
  "type": 2,
  "frequency": {
    "type": 1,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 30,
    "unit": "minutes"
  },
  "milestone": {
    "target": 100
  }
}

### Partially Update Habit
PATCH {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}}
Accept: application/json
Content-Type: application/json

[
  {
    "op": "replace",
    "path": "/name",
    "value": "Daily Coding (Update)"
  },
  {
    "op": "remove",
    "path": "/description"
  }
]

### Delete Habit
DELETE  {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}}
Accept: application/json
