@basePath = api/habits
@habitId = h_01972355-6f47-7227-9838-0ca60418594f

### Get Habits
GET {{devHabitApiHostAddress}}/{{basePath}}
Authorization: Bearer {{token}}
Accept: application/vnd.dev-habit.hateoas+json
# Accept: application/json

### Get Habit by Id
GET {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}}
Authorization: Bearer {{token}}
Accept: application/vnd.dev-habit.hateoas+json
# Accept: application/json

### Create Habit
POST {{devHabitApiHostAddress}}/{{basePath}}
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "Daily coding",
  "description": null,
  "type": 2,
  "frequency": {
    "type": 2,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 30,
    "unit": "minutes"
  },
  "milestone": {
    "target": 1
  },
  "endDate": "2025-12-01"
}

### Update Habit
PUT {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}}
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "Daily coding",
  "description": "The new description",
  "type": 2,
  "frequency": {
    "type": 2,
    "timesPerPeriod": 1
  },
  "target": {
    "value": 30,
    "unit": "minutes"
  },
  "milestone": {
    "target": 100
  }
}

### Partially Update Habit
PATCH {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}}
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

[
  {
    "op": "replace",
    "path": "/name",
    "value": "Daily Coding (Update)"
  },
  {
    "op": "remove",
    "path": "/description"
  }
]

### Delete Habit
DELETE  {{devHabitApiHostAddress}}/{{basePath}}/{{habitId}}
Authorization: Bearer {{token}}
Accept: application/json
