@DevHabitApiHostAddress = https://localhost:5001
@HabitId = h_01962bc2-765b-7e35-846e-42568b36975b
@BasePath = api/habits/{{HabitId}}/tags
@TagId = t_019630d0-d41f-75bb-901a-e74d41bf62ca

### Upsert Habit Tags
PUT {{DevHabitApiHostAddress}}/{{BasePath}}
Accept: application/json
Content-Type: application/json

{
  "tagIds": [
    "t_0196350a-0a40-7195-aba3-f759778f9262",
    "t_019630d0-d41f-75bb-901a-e74d41bf62ca"
  ]
}

### Delete Habit Tag
Delete {{DevHabitApiHostAddress}}/{{BasePath}}/{{TagId}}
Accept: application/json
