@DevHabitApiHostAddress = https://localhost:5001
@BasePath = api/tags
@ResourceId = t_01962fec-fe05-749f-ae01-3d78000389ce

### Get Tags
GET {{DevHabitApiHostAddress}}/{{BasePath}}
Accept: application/json

### Get Tag by Id
GET {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}}
Accept: application/json

### Create Tag
POST {{DevHabitApiHostAddress}}/{{BasePath}}
Accept: application/json
Content-Type: application/json

{
  "name": "coding",
  "description": null
}

### Update Tag
PUT {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}}
Accept: application/json
Content-Type: application/json

{
  "name": "coding",
  "description": "The new description"
}

### Delete Tag
DELETE  {{DevHabitApiHostAddress}}/{{BasePath}}/{{ResourceId}}
Accept: application/json
