@basePath = api/tags
@tagId = t_0196350a-0a40-7195-aba3-f759778f9262

### Get Tags
GET {{devHabitApiHostAddress}}/{{basePath}}
Accept: application/vnd.dev-habit.hateoas+json
# Accept: application/json

### Get Tag by Id
GET {{devHabitApiHostAddress}}/{{basePath}}/{{tagId}}
Accept: application/vnd.dev-habit.hateoas+json
# Accept: application/json

### Create Tag
POST {{devHabitApiHostAddress}}/{{basePath}}
Accept: application/json
Content-Type: application/json

{
  "name": "Coding",
  "description": null
}

### Update Tag
PUT {{devHabitApiHostAddress}}/{{basePath}}/{{tagId}}
Accept: application/json
Content-Type: application/json

{
  "name": "Coding",
  "description": "The new description"
}

### Delete Tag
DELETE  {{devHabitApiHostAddress}}/{{basePath}}/{{tagId}}
Accept: application/json
