@basePath = api/tags
@tagId = t_01972353-5acd-7aef-918d-0b73a3904d94

### Get Tags
GET {{devHabitApiHostAddress}}/{{basePath}}
Authorization: Bearer {{token}}
Accept: application/vnd.dev-habit.hateoas+json
# Accept: application/json

### Get Tag by Id
GET {{devHabitApiHostAddress}}/{{basePath}}/{{tagId}}
Authorization: Bearer {{token}}
Accept: application/vnd.dev-habit.hateoas+json
# Accept: application/json

### Create Tag
POST {{devHabitApiHostAddress}}/{{basePath}}
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": ".net",
  "description": null
}

### Update Tag
PUT {{devHabitApiHostAddress}}/{{basePath}}/{{tagId}}
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "Coding",
  "description": "The new description"
}

### Delete Tag
DELETE  {{devHabitApiHostAddress}}/{{basePath}}/{{tagId}}
Authorization: Bearer {{token}}
Accept: application/json
